from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .paths import RepoPaths
from .registry import load_cards
from .scoring import default_score_for_bridge


def build_lean_bridge_report(paths: RepoPaths) -> str:
    cards = load_cards(paths)
    bridges = [doc for doc in cards if doc.meta.get("type") == "bridge"]
    rows: list[dict[str, Any]] = []
    for bridge in bridges:
        bid = str(bridge.meta.get("id"))
        score = default_score_for_bridge(bid)
        rows.append({
            "id": bid,
            "title": bridge.meta.get("title", "Untitled"),
            "status": bridge.meta.get("status", "unknown"),
            "lean_priority": bridge.meta.get("lean_priority", "unknown"),
            "score": score.total,
            "label": score.label,
            "path": str(bridge.path.relative_to(paths.root)),
        })
    priority_rank = {"high": 0, "medium": 1, "low": 2, "unknown": 3}
    rows.sort(key=lambda r: (priority_rank.get(str(r["lean_priority"]), 3), -int(r["score"])))

    lines = [
        "# Lean Bridge Candidate Report",
        "",
        "Generated by `python bridge.py seek-lean-bridge`.",
        "",
        "## Ranked candidates",
        "",
        "| Rank | ID | Title | Lean priority | Score | Label | Status |",
        "|---:|---|---|---|---:|---|---|",
    ]
    for i, row in enumerate(rows, 1):
        lines.append(f"| {i} | {row['id']} | {row['title']} | {row['lean_priority']} | {row['score']} | {row['label']} | {row['status']} |")
    lines.extend([
        "",
        "## Recommended next action",
        "",
        "`B-0006` is the current finite-sieve breakthrough: wheel-shadow distribution turns resonance/survival language into exact finite-wheel candidate counts.",
        "",
        "Closed mirror calibration:",
        "",
        "```text",
        "For natural digits a b, 11 divides 1000*a + 100*b + 10*b + a.",
        "```",
        "",
        "Closed PrimeBridge calibration:",
        "",
        "```text",
        "For prime p > 3, digital_root_10 p is not 3, 6, or 9.",
        "```",
        "",
        "Closed prime-structural theorem:",
        "",
        "```text",
        "For every n, one of n, n+2, n+4 is divisible by 3; if all three are prime, the triplet is 3,5,7.",
        "```",
        "",
        "Search-enabling bridge:",
        "",
        "```text",
        "Compute shadow_p(H), gate deficits, admissibility witnesses, local survival factors, and empirical prime-translate counts.",
        "```",
        "",
        "Finite-sieve distribution bridge:",
        "",
        "```text",
        "|R_W(H)| = prod_{p | W} (p - nu_p(H))",
        "```",
        "",
        "Current Lean breakthrough:",
        "",
        "```text",
        "bt0006_squarefree_wheel_shadow_distribution proves the finite-wheel product theorem for arbitrary finite positive pairwise-coprime gate lists.",
        "```",
        "",
        "Closed structural maximizer theorem:",
        "",
        "```text",
        "BT-0008 proves that absolute finite resonance maximizers are exactly gate-product lattice patterns.",
        "```",
        "",
        "Next non-calibration theorem target:",
        "",
        "```text",
        "BT-0009: classify subcritical maximizers when D < (k - 1) * gateProduct gates.",
        "```",
        "",
        "The prime digital-root theorem is shallow-real; BT-0006 and BT-0008 are finite-sieve / combinatorics results, not actual prime-distribution theorems.",
    ])
    return "\n".join(lines) + "\n"


def write_lean_bridge_report(paths: RepoPaths) -> Path:
    paths.reports.mkdir(parents=True, exist_ok=True)
    path = paths.reports / "lean_bridge_candidates.md"
    path.write_text(build_lean_bridge_report(paths), encoding="utf-8")
    return path


def summarize_result_json(path: Path) -> str:
    data = json.loads(path.read_text(encoding="utf-8"))
    return f"{data.get('id')}: {data.get('verdict')} — {data.get('summary')}"
