/-
BT-0008 resonance lattice maximizer theorem.

This file turns the BT-0007 finite resonance search into a structural theorem:
for zero-anchored patterns, the product of local survivor counts is bounded by
the product of the one-shadow local maxima, and equality is exactly the lattice
condition that every offset is divisible by the full gate product.

The result is finite-sieve combinatorics. It does not assert anything about the
distribution of actual primes.
-/

import Lean.Elab.Tactic.Omega
import NumBridge.ResonanceOptimization

namespace NumBridge

/-- A gate list whose moduli are all greater than one. -/
def GatesAboveOne (gates : List Nat) : Prop :=
  ∀ p : Nat, p ∈ gates → 1 < p

/-- A list-level no-duplicate predicate for offset patterns. -/
def ListAllDistinct (offsets : List Nat) : Prop :=
  offsets.Nodup

/-- A normalized offset list starts with zero. -/
def StartsAtZeroProp : List Nat → Prop
  | [] => False
  | h :: _ => h = 0

/-- Every offset lies within the diameter bound `D`. -/
def AllOffsetsLE (D : Nat) (offsets : List Nat) : Prop :=
  ∀ h : Nat, h ∈ offsets → h ≤ D

/-- Distinct, zero-starting, bounded `k`-point offset pattern. -/
def NormalizedDistinctPattern (k D : Nat) (offsets : List Nat) : Prop :=
  StartsAtZeroProp offsets ∧ offsets.length = k ∧ offsets.Nodup ∧ AllOffsetsLE D offsets

/-- The absolute product upper bound: each local shadow contains at least zero. -/
def ResonanceUpperBound (gates : List Nat) : Nat :=
  gates.foldr (fun p acc => (p - 1) * acc) 1

/-- Every offset lies on the lattice generated by `W`. -/
def AllOffsetsDivisibleBy (W : Nat) (offsets : List Nat) : Prop :=
  ∀ h : Nat, h ∈ offsets → W ∣ h

/-- The canonical lattice pattern `[0, W, 2W, ..., (k-1)W]`. -/
def CanonicalResonanceLatticePattern (k W : Nat) : List Nat :=
  (List.range k).map (fun i => i * W)

/-- A greater-than-one gate list is positive in the BT-0006 sense. -/
theorem positiveGates_of_gatesAboveOne {gates : List Nat} (hgt : GatesAboveOne gates) :
    PositiveGates gates := by
  intro p hp
  have h : 1 < p := hgt p hp
  omega

/-- `StartsAtZeroProp` supplies the zero offset as a member. -/
theorem startsAtZero_mem_zero {offsets : List Nat} (hstart : StartsAtZeroProp offsets) :
    0 ∈ offsets := by
  cases offsets with
  | nil => cases hstart
  | cons h t =>
      simp [StartsAtZeroProp] at hstart
      subst h
      simp

/-- Count all nonzero residues in `range p`. -/
theorem countP_nonzero_range (p : Nat) :
    (List.range p).countP (fun a => ¬(a == 0)) = p - 1 := by
  induction p with
  | zero =>
      simp
  | succ n ih =>
      rw [List.range_succ, List.countP_append]
      change (List.range n).countP (fun a => ¬(a == 0)) +
          ([n].countP (fun a => ¬(a == 0))) = n
      rw [ih]
      by_cases hn : n = 0
      · subst n
        simp
      · simp [hn]
        omega

/-- Adding an offset whose residue is zero does not change the residue. -/
theorem add_mod_eq_left_of_right_mod_zero {a h p : Nat} (hh : h % p = 0) :
    (a + h) % p = a % p := by
  rw [Nat.add_mod, hh]
  simp

/-- If every offset is zero modulo `p`, the local survivor count is `p - 1`. -/
theorem local_survivor_count_eq_p_minus_one_of_all_mod_zero
    (p : Nat) (offsets : List Nat) (_hp : 0 < p) (hzero : 0 ∈ offsets)
    (hall : ∀ h : Nat, h ∈ offsets → h % p = 0) :
    LocalGateSurvivorCount p offsets = p - 1 := by
  unfold LocalGateSurvivorCount GateGoodResidue GateBadResidue
  have hcongr : ∀ a : Nat, a ∈ List.range p →
      (offsets.any (fun h => (a + h) % p == 0)) = (a == 0) := by
    intro a ha
    by_cases ha0 : a = 0
    · subst a
      simp
      exact ⟨0, hzero, hall 0 hzero⟩
    · have hany : offsets.any (fun h => (a + h) % p == 0) = false := by
        apply Bool.eq_false_iff.mpr
        intro htrue
        rcases List.any_eq_true.mp htrue with ⟨h, hhmem, hbad⟩
        have hhmod : h % p = 0 := hall h hhmem
        have hadd : (a + h) % p = a % p := add_mod_eq_left_of_right_mod_zero hhmod
        have hzero_mod : (a + h) % p = 0 := beq_iff_eq.mp hbad
        have hamod : a % p = 0 := by rwa [hadd] at hzero_mod
        have ha_lt : a < p := List.mem_range.mp ha
        have ha_eq : a = 0 := by
          rw [Nat.mod_eq_of_lt ha_lt] at hamod
          exact hamod
        exact ha0 ha_eq
      simp [hany, ha0]
  have hcount :
      (List.range p).countP (fun a => ¬offsets.any (fun h => (a + h) % p == 0)) =
        (List.range p).countP (fun a => ¬(a == 0)) := by
    apply List.countP_congr
    intro a ha
    rw [hcongr a ha]
  rw [hcount, countP_nonzero_range]

/-- A zero-anchored pattern shadows at least one local residue. -/
theorem nonempty_shadow_count_ge_one
    (p : Nat) (offsets : List Nat) (hp : 0 < p) (hzero : 0 ∈ offsets) :
    1 ≤ LocalResidueShadowCount p offsets := by
  unfold LocalResidueShadowCount
  rw [List.countP_eq_length_filter]
  apply Nat.succ_le_of_lt
  rw [List.length_pos_iff_exists_mem]
  refine ⟨0, ?_⟩
  exact List.mem_filter.mpr ⟨List.mem_range.mpr hp, by
    unfold GateBadResidue
    exact List.any_eq_true.mpr ⟨0, hzero, by simp⟩⟩

/-- A local shadow count is bounded by the modulus. -/
theorem local_shadow_count_le_p (p : Nat) (offsets : List Nat) :
    LocalResidueShadowCount p offsets ≤ p := by
  unfold LocalResidueShadowCount
  rw [List.countP_eq_length_filter]
  simpa using List.length_filter_le (GateBadResidue p offsets) (List.range p)

/-- A zero-anchored local survivor count is at most `p - 1`. -/
theorem local_survivor_count_le_p_minus_one
    (p : Nat) (offsets : List Nat) (hp : 0 < p) (hzero : 0 ∈ offsets) :
    LocalGateSurvivorCount p offsets ≤ p - 1 := by
  rw [local_gate_survivor_count_eq_modulus_sub_shadow]
  have hshadow_ge : 1 ≤ LocalResidueShadowCount p offsets :=
    nonempty_shadow_count_ge_one p offsets hp hzero
  have hshadow_le : LocalResidueShadowCount p offsets ≤ p :=
    local_shadow_count_le_p p offsets
  omega

/-- BT-0008A: finite resonance numerator is bounded by the product upper bound. -/
theorem finite_resonance_numerator_le_upper_bound
    (gates offsets : List Nat) (hpos : PositiveGates gates) (hzero : 0 ∈ offsets) :
    FiniteResonanceNumerator gates offsets ≤ ResonanceUpperBound gates := by
  induction gates with
  | nil =>
      simp [FiniteResonanceNumerator, ProductLocalGateSurvivorCount, ResonanceUpperBound]
  | cons p ps ih =>
      have hp : 0 < p := hpos p (by simp)
      have hpos_ps : PositiveGates ps := by
        intro q hq
        exact hpos q (by simp [hq])
      change LocalGateSurvivorCount p offsets * ProductLocalGateSurvivorCount ps offsets ≤
        (p - 1) * ResonanceUpperBound ps
      exact Nat.mul_le_mul (local_survivor_count_le_p_minus_one p offsets hp hzero)
        (ih hpos_ps)

/-- If all offsets lie on the gate-product lattice, they attain the product upper bound. -/
theorem finite_resonance_numerator_eq_upper_bound_of_offsets_dvd_gateProduct
    (gates offsets : List Nat) (hpos : PositiveGates gates)
    (hzero : 0 ∈ offsets) (hall : AllOffsetsDivisibleBy (gateProduct gates) offsets) :
    FiniteResonanceNumerator gates offsets = ResonanceUpperBound gates := by
  induction gates with
  | nil =>
      simp [FiniteResonanceNumerator, ProductLocalGateSurvivorCount, ResonanceUpperBound]
  | cons p ps ih =>
      have hp : 0 < p := hpos p (by simp)
      have hpos_ps : PositiveGates ps := by
        intro q hq
        exact hpos q (by simp [hq])
      have hallp : ∀ h : Nat, h ∈ offsets → h % p = 0 := by
        intro h hh
        have hWdvdh : gateProduct (p :: ps) ∣ h := hall h hh
        have hpdvdW : p ∣ gateProduct (p :: ps) := dvd_gateProduct_of_mem (by simp)
        exact Nat.mod_eq_zero_of_dvd (Nat.dvd_trans hpdvdW hWdvdh)
      have hallps : AllOffsetsDivisibleBy (gateProduct ps) offsets := by
        intro h hh
        have hWdvdh : gateProduct (p :: ps) ∣ h := hall h hh
        have htaildvdW : gateProduct ps ∣ gateProduct (p :: ps) := by
          unfold gateProduct
          exact Nat.dvd_mul_left (gateProduct ps) p
        exact Nat.dvd_trans htaildvdW hWdvdh
      change LocalGateSurvivorCount p offsets * ProductLocalGateSurvivorCount ps offsets =
        (p - 1) * ResonanceUpperBound ps
      have htail := ih hpos_ps hallps
      unfold FiniteResonanceNumerator at htail
      rw [local_survivor_count_eq_p_minus_one_of_all_mod_zero p offsets hp hzero hallp, htail]

/-- A nodup length-one list has only one possible member. -/
theorem nodup_length_one_mem_eq {l : List Nat} (hnd : l.Nodup) (hlen : l.length = 1)
    {a b : Nat} (ha : a ∈ l) (hb : b ∈ l) : a = b := by
  cases l with
  | nil =>
      cases ha
  | cons x xs =>
      cases xs with
      | nil =>
          simp at ha hb
          subst a
          subst b
          rfl
      | cons y ys =>
          simp at hlen

/-- Two true entries in a range predicate with count one must be the same entry. -/
theorem countP_eq_one_mem_eq_range {p : Nat} {P : Nat → Bool} {a b : Nat}
    (hcount : (List.range p).countP P = 1)
    (ha : a ∈ List.range p) (hpa : P a = true)
    (hb : b ∈ List.range p) (hpb : P b = true) :
    a = b := by
  let filtered := (List.range p).filter P
  have hlen : filtered.length = 1 := by
    unfold filtered
    rwa [List.countP_eq_length_filter] at hcount
  have hnd : filtered.Nodup := by
    unfold filtered
    exact List.Sublist.nodup List.filter_sublist List.nodup_range
  have haf : a ∈ filtered := by
    unfold filtered
    exact List.mem_filter.mpr ⟨ha, hpa⟩
  have hbf : b ∈ filtered := by
    unfold filtered
    exact List.mem_filter.mpr ⟨hb, hpb⟩
  exact nodup_length_one_mem_eq hnd hlen haf hbf

/--
Local equality characterization: a zero-anchored pattern reaches `p - 1`
survivors exactly when every offset is zero modulo `p`.
-/
theorem local_survivor_count_eq_p_minus_one_iff_all_mod_zero
    (p : Nat) (offsets : List Nat) (hp : 0 < p) (hzero : 0 ∈ offsets) :
    LocalGateSurvivorCount p offsets = p - 1 ↔
      ∀ h : Nat, h ∈ offsets → h % p = 0 := by
  constructor
  · intro hsurv h hh
    have hshadow_ge : 1 ≤ LocalResidueShadowCount p offsets :=
      nonempty_shadow_count_ge_one p offsets hp hzero
    have hshadow_le : LocalResidueShadowCount p offsets ≤ p :=
      local_shadow_count_le_p p offsets
    have hshadow : LocalResidueShadowCount p offsets = 1 := by
      rw [local_gate_survivor_count_eq_modulus_sub_shadow] at hsurv
      omega
    let r := h % p
    by_cases hr0 : r = 0
    · exact hr0
    · have hrlt : r < p := by
        unfold r
        exact Nat.mod_lt h hp
      have hrpos : 0 < r := Nat.pos_of_ne_zero hr0
      let a := p - r
      have halt : a < p := by
        unfold a
        omega
      have hbad0 : GateBadResidue p offsets 0 = true := by
        unfold GateBadResidue
        exact List.any_eq_true.mpr ⟨0, hzero, by simp⟩
      have hbada : GateBadResidue p offsets a = true := by
        unfold GateBadResidue
        apply List.any_eq_true.mpr
        refine ⟨h, hh, ?_⟩
        apply beq_iff_eq.mpr
        calc
          (a + h) % p = ((a % p) + (h % p)) % p := by rw [Nat.add_mod]
          _ = (a + r) % p := by rw [Nat.mod_eq_of_lt halt]
          _ = p % p := by
              congr
              unfold a
              omega
          _ = 0 := Nat.mod_self p
      have haeq0 : a = 0 := by
        exact (countP_eq_one_mem_eq_range (p := p) (P := GateBadResidue p offsets)
          (a := 0) (b := a) hshadow (List.mem_range.mpr hp) hbad0
          (List.mem_range.mpr halt) hbada).symm
      unfold a at haeq0
      omega
  · exact local_survivor_count_eq_p_minus_one_of_all_mod_zero p offsets hp hzero

/-- The product upper bound is positive for gates greater than one. -/
theorem resonance_upper_bound_pos {gates : List Nat} (hgt : GatesAboveOne gates) :
    0 < ResonanceUpperBound gates := by
  induction gates with
  | nil =>
      simp [ResonanceUpperBound]
  | cons p ps ih =>
      have hp : 1 < p := hgt p (by simp)
      have hps : GatesAboveOne ps := by
        intro q hq
        exact hgt q (by simp [hq])
      unfold ResonanceUpperBound
      exact Nat.mul_pos (by omega) (ih hps)

/-- Product equality forces every local gate to attain its one-shadow maximum. -/
theorem equality_upper_bound_implies_single_shadow_each_gate
    (gates offsets : List Nat) (hgt : GatesAboveOne gates) (hzero : 0 ∈ offsets)
    (heq : FiniteResonanceNumerator gates offsets = ResonanceUpperBound gates) :
    ∀ p : Nat, p ∈ gates → LocalGateSurvivorCount p offsets = p - 1 := by
  induction gates with
  | nil =>
      intro p hp
      cases hp
  | cons p ps ih =>
      have hpgt : 1 < p := hgt p (by simp)
      have hp : 0 < p := by omega
      have hgt_ps : GatesAboveOne ps := by
        intro q hq
        exact hgt q (by simp [hq])
      have hpos_ps : PositiveGates ps := positiveGates_of_gatesAboveOne hgt_ps
      have htail_pos : 0 < ResonanceUpperBound ps := resonance_upper_bound_pos hgt_ps
      have hlocal_le : LocalGateSurvivorCount p offsets ≤ p - 1 :=
        local_survivor_count_le_p_minus_one p offsets hp hzero
      have htail_le : ProductLocalGateSurvivorCount ps offsets ≤ ResonanceUpperBound ps := by
        have h := finite_resonance_numerator_le_upper_bound ps offsets hpos_ps hzero
        unfold FiniteResonanceNumerator at h
        exact h
      change LocalGateSurvivorCount p offsets * ProductLocalGateSurvivorCount ps offsets =
        (p - 1) * ResonanceUpperBound ps at heq
      have hp_eq : LocalGateSurvivorCount p offsets = p - 1 := by
        by_cases hEq : LocalGateSurvivorCount p offsets = p - 1
        · exact hEq
        · have hlt : LocalGateSurvivorCount p offsets < p - 1 :=
            Nat.lt_of_le_of_ne hlocal_le hEq
          have hmul_le : LocalGateSurvivorCount p offsets * ProductLocalGateSurvivorCount ps offsets ≤
              LocalGateSurvivorCount p offsets * ResonanceUpperBound ps :=
            Nat.mul_le_mul_left (LocalGateSurvivorCount p offsets) htail_le
          have hmul_lt : LocalGateSurvivorCount p offsets * ResonanceUpperBound ps <
              (p - 1) * ResonanceUpperBound ps :=
            Nat.mul_lt_mul_of_pos_right hlt htail_pos
          have hcontr : LocalGateSurvivorCount p offsets * ProductLocalGateSurvivorCount ps offsets <
              (p - 1) * ResonanceUpperBound ps :=
            Nat.lt_of_le_of_lt hmul_le hmul_lt
          rw [heq] at hcontr
          exact False.elim (Nat.lt_irrefl _ hcontr)
      have htail_eq : FiniteResonanceNumerator ps offsets = ResonanceUpperBound ps := by
        unfold FiniteResonanceNumerator
        have heqtail : (p - 1) * ProductLocalGateSurvivorCount ps offsets =
            (p - 1) * ResonanceUpperBound ps := by
          rwa [hp_eq] at heq
        exact Nat.mul_left_cancel (by omega : 0 < p - 1) heqtail
      intro q hq
      simp at hq
      rcases hq with rfl | hqps
      · exact hp_eq
      · exact ih hgt_ps htail_eq q hqps

/-- A gate product divides `h` iff every pairwise-coprime gate divides `h`. -/
theorem dvd_gateProduct_iff_all_gates_dvd
    (gates : List Nat) (hcop : PairwiseCoprime gates) (h : Nat) :
    gateProduct gates ∣ h ↔ ∀ p : Nat, p ∈ gates → p ∣ h := by
  constructor
  · intro hW p hp
    exact Nat.dvd_trans (dvd_gateProduct_of_mem hp) hW
  · intro hall
    induction gates with
    | nil =>
        simp [gateProduct]
    | cons p ps ih =>
        have hp_dvd : p ∣ h := hall p (by simp)
        have hcop_ps : PairwiseCoprime ps := (List.pairwise_cons.mp hcop).right
        have hprod_dvd : gateProduct ps ∣ h := by
          apply ih hcop_ps
          intro q hq
          exact hall q (by simp [hq])
        have hcop_prod_p : Nat.Coprime (gateProduct ps) p :=
          gateProduct_coprime_head_of_pairwise hcop
        change p * gateProduct ps ∣ h
        rw [Nat.mul_comm p (gateProduct ps)]
        exact hcop_prod_p.mul_dvd_of_dvd_of_dvd hprod_dvd hp_dvd

/-- Same residue as zero across all gates is equivalent to divisibility by their product. -/
theorem same_residue_as_zero_all_gates_iff_dvd_gateProduct
    (gates : List Nat) (hcop : PairwiseCoprime gates) (h : Nat) :
    gateProduct gates ∣ h ↔ ∀ p : Nat, p ∈ gates → h % p = 0 := by
  rw [dvd_gateProduct_iff_all_gates_dvd gates hcop h]
  constructor
  · intro hall p hp
    exact Nat.mod_eq_zero_of_dvd (hall p hp)
  · intro hall p hp
    exact Nat.dvd_of_mod_eq_zero (hall p hp)

/-- BT-0008B: equality holds exactly on the full gate-product lattice. -/
theorem resonance_upper_bound_eq_iff_offsets_dvd_gateProduct
    (gates offsets : List Nat) (hgt : GatesAboveOne gates) (hcop : PairwiseCoprime gates)
    (hzero : 0 ∈ offsets) :
    FiniteResonanceNumerator gates offsets = ResonanceUpperBound gates ↔
      AllOffsetsDivisibleBy (gateProduct gates) offsets := by
  constructor
  · intro heq h hh
    apply (same_residue_as_zero_all_gates_iff_dvd_gateProduct gates hcop h).mpr
    intro p hp
    have hpgt : 1 < p := hgt p hp
    have hp0 : 0 < p := by omega
    have hlocal : LocalGateSurvivorCount p offsets = p - 1 :=
      equality_upper_bound_implies_single_shadow_each_gate gates offsets hgt hzero heq p hp
    exact (local_survivor_count_eq_p_minus_one_iff_all_mod_zero p offsets hp0 hzero).mp
      hlocal h hh
  · intro hall
    exact finite_resonance_numerator_eq_upper_bound_of_offsets_dvd_gateProduct gates offsets
      (positiveGates_of_gatesAboveOne hgt) hzero hall

/-- BT-0008 core theorem: upper bound plus lattice equality characterization. -/
theorem bt0008_resonance_lattice_maximizer_theorem
    (gates offsets : List Nat) (hgt : GatesAboveOne gates) (hcop : PairwiseCoprime gates)
    (hstart : StartsAtZeroProp offsets) :
    FiniteResonanceNumerator gates offsets ≤ ResonanceUpperBound gates ∧
      (FiniteResonanceNumerator gates offsets = ResonanceUpperBound gates ↔
        AllOffsetsDivisibleBy (gateProduct gates) offsets) := by
  have hzero := startsAtZero_mem_zero hstart
  exact ⟨finite_resonance_numerator_le_upper_bound gates offsets
      (positiveGates_of_gatesAboveOne hgt) hzero,
    resonance_upper_bound_eq_iff_offsets_dvd_gateProduct gates offsets hgt hcop hzero⟩

/-- The canonical lattice pattern starts at zero for `k > 0`. -/
theorem canonical_lattice_pattern_startsAtZero {k W : Nat} (hk : 0 < k) :
    StartsAtZeroProp (CanonicalResonanceLatticePattern k W) := by
  cases k with
  | zero =>
      cases hk
  | succ n =>
      unfold CanonicalResonanceLatticePattern
      rw [List.range_succ_eq_map]
      simp [StartsAtZeroProp]

/-- The canonical lattice pattern has length `k`. -/
theorem canonical_lattice_pattern_length (k W : Nat) :
    (CanonicalResonanceLatticePattern k W).length = k := by
  simp [CanonicalResonanceLatticePattern]

/-- The canonical lattice pattern has no duplicates when `W > 0`. -/
theorem canonical_lattice_pattern_nodup {k W : Nat} (hW : 0 < W) :
    (CanonicalResonanceLatticePattern k W).Nodup := by
  unfold CanonicalResonanceLatticePattern
  have hpairRange : (List.range k).Pairwise (fun a b => a ≠ b) :=
    List.nodup_iff_pairwise_ne.mp List.nodup_range
  have hpairMap : ((List.range k).map (fun i => i * W)).Pairwise (fun a b => a ≠ b) := by
    exact List.Pairwise.map (fun i => i * W)
      (fun a b hne heq => hne (Nat.mul_right_cancel hW heq)) hpairRange
  exact List.nodup_iff_pairwise_ne.mpr hpairMap

/-- The canonical lattice pattern lies below `D` if `(k - 1)W ≤ D`. -/
theorem canonical_lattice_pattern_offsets_le_if_D_ge
    {k W D : Nat} (hD : (k - 1) * W ≤ D) :
    AllOffsetsLE D (CanonicalResonanceLatticePattern k W) := by
  intro h hh
  unfold CanonicalResonanceLatticePattern at hh
  rcases List.mem_map.mp hh with ⟨i, hi, rfl⟩
  have hik : i < k := List.mem_range.mp hi
  have hi_le : i ≤ k - 1 := Nat.le_sub_one_of_lt hik
  have himul : i * W ≤ (k - 1) * W := Nat.mul_le_mul_right W hi_le
  exact Nat.le_trans himul hD

/-- Every canonical lattice offset is divisible by `W`. -/
theorem canonical_lattice_pattern_all_offsets_dvd
    (k W : Nat) :
    AllOffsetsDivisibleBy W (CanonicalResonanceLatticePattern k W) := by
  intro h hh
  unfold CanonicalResonanceLatticePattern at hh
  rcases List.mem_map.mp hh with ⟨i, _, rfl⟩
  exact Nat.dvd_mul_left W i

/-- BT-0008C, sufficient half: the canonical lattice pattern is valid above the threshold. -/
theorem canonical_lattice_pattern_valid_if_D_ge
    {gates : List Nat} {k D : Nat} (hk : 0 < k) (hpos : PositiveGates gates)
    (hD : (k - 1) * gateProduct gates ≤ D) :
    NormalizedDistinctPattern k D (CanonicalResonanceLatticePattern k (gateProduct gates)) := by
  have hW : 0 < gateProduct gates := gateProduct_pos_of_positive hpos
  exact ⟨canonical_lattice_pattern_startsAtZero (W := gateProduct gates) hk,
    canonical_lattice_pattern_length k (gateProduct gates),
    canonical_lattice_pattern_nodup hW,
    canonical_lattice_pattern_offsets_le_if_D_ge hD⟩

/-- The canonical lattice pattern attains the product upper bound. -/
theorem canonical_lattice_pattern_attains_upper_bound
    (gates : List Nat) (k : Nat) (hk : 0 < k) (hpos : PositiveGates gates) :
    FiniteResonanceNumerator gates (CanonicalResonanceLatticePattern k (gateProduct gates)) =
      ResonanceUpperBound gates := by
  have hzero : 0 ∈ CanonicalResonanceLatticePattern k (gateProduct gates) :=
    startsAtZero_mem_zero (canonical_lattice_pattern_startsAtZero (W := gateProduct gates) hk)
  exact finite_resonance_numerator_eq_upper_bound_of_offsets_dvd_gateProduct gates
    (CanonicalResonanceLatticePattern k (gateProduct gates)) hpos hzero
    (canonical_lattice_pattern_all_offsets_dvd k (gateProduct gates))

/-- Above the lattice threshold, an upper-bound-attaining normalized pattern exists. -/
theorem bt0008_attainability_threshold_sufficient
    (gates : List Nat) (k D : Nat) (hk : 0 < k) (hpos : PositiveGates gates)
    (hD : (k - 1) * gateProduct gates ≤ D) :
    ∃ offsets : List Nat,
      NormalizedDistinctPattern k D offsets ∧
      FiniteResonanceNumerator gates offsets = ResonanceUpperBound gates := by
  refine ⟨CanonicalResonanceLatticePattern k (gateProduct gates), ?_, ?_⟩
  · exact canonical_lattice_pattern_valid_if_D_ge hk hpos hD
  · exact canonical_lattice_pattern_attains_upper_bound gates k hk hpos

/--
BT-0008D, upper-bound family characterization.

Among normalized distinct patterns, the absolute product upper bound is attained
exactly by offsets lying in the gate-product lattice. The converse threshold
claim that such a `k`-point family exists only when `(k - 1)W ≤ D` remains a
separate finite pigeonhole/order theorem.
-/
theorem bt0008_maximizer_family_characterization
    (gates offsets : List Nat) (k D : Nat)
    (hgt : GatesAboveOne gates) (hcop : PairwiseCoprime gates)
    (hpat : NormalizedDistinctPattern k D offsets) :
    FiniteResonanceNumerator gates offsets = ResonanceUpperBound gates ↔
      AllOffsetsDivisibleBy (gateProduct gates) offsets := by
  exact resonance_upper_bound_eq_iff_offsets_dvd_gateProduct gates offsets hgt hcop
    (startsAtZero_mem_zero hpat.left)

end NumBridge
